Corpus corpus_1's weight should be given. We default it to 1 for you.
[2023-01-05 10:04:13,290 INFO] Counter vocab from -1 samples.
[2023-01-05 10:04:13,290 INFO] n_sample=-1: Build vocab on full datasets.
[2023-01-05 10:05:02,067 INFO] Counters src:112
[2023-01-05 10:05:02,067 INFO] Counters tgt:108
Traceback (most recent call last):
  File ".venv/bin/onmt_build_vocab", line 8, in <module>
    sys.exit(main())
  File "/auto/brno2/home/souradat/rp-sourada/czech-automatic-inflection/.venv/lib/python3.8/site-packages/onmt/bin/build_vocab.py", line 200, in main
    build_vocab_main(opts)
  File "/auto/brno2/home/souradat/rp-sourada/czech-automatic-inflection/.venv/lib/python3.8/site-packages/onmt/bin/build_vocab.py", line 184, in build_vocab_main
    save_counter(src_counter, opts.src_vocab)
  File "/auto/brno2/home/souradat/rp-sourada/czech-automatic-inflection/.venv/lib/python3.8/site-packages/onmt/bin/build_vocab.py", line 173, in save_counter
    check_path(save_path, exist_ok=opts.overwrite, log=logger.warning)
  File "/auto/brno2/home/souradat/rp-sourada/czech-automatic-inflection/.venv/lib/python3.8/site-packages/onmt/utils/misc.py", line 47, in check_path
    raise IOError(f"path {path} exists, stop.")
OSError: path data/inner/onmt/run/example.vocab.src exists, stop.
Traceback (most recent call last):
  File ".venv/bin/onmt_translate", line 8, in <module>
    sys.exit(main())
  File "/auto/brno2/home/souradat/rp-sourada/czech-automatic-inflection/.venv/lib/python3.8/site-packages/onmt/bin/translate.py", line 60, in main
    translate(opt)
  File "/auto/brno2/home/souradat/rp-sourada/czech-automatic-inflection/.venv/lib/python3.8/site-packages/onmt/bin/translate.py", line 23, in translate
    translator = build_translator(opt, logger=logger,
  File "/auto/brno2/home/souradat/rp-sourada/czech-automatic-inflection/.venv/lib/python3.8/site-packages/onmt/translate/translator.py", line 31, in build_translator
    vocabs, model, model_opt = load_test_model(opt)
  File "/auto/brno2/home/souradat/rp-sourada/czech-automatic-inflection/.venv/lib/python3.8/site-packages/onmt/model_builder.py", line 91, in load_test_model
    checkpoint = torch.load(model_path,
  File "/auto/brno2/home/souradat/rp-sourada/czech-automatic-inflection/.venv/lib/python3.8/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/auto/brno2/home/souradat/rp-sourada/czech-automatic-inflection/.venv/lib/python3.8/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/auto/brno2/home/souradat/rp-sourada/czech-automatic-inflection/.venv/lib/python3.8/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'data/inner/onmt/run/model50_step_3000.pt'
